import type { INodeProperties } from 'n8n-workflow';

export const coverLetterOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['coverLetter'] } },
		options: [
			{ name: 'Copy From Resume', value: 'copyFromResume', action: 'Copy an embedded cover letter', description: 'Create a saved cover letter from a resume item' },
			{ name: 'Create', value: 'create', action: 'Create a cover letter', description: 'Create a saved cover letter' },
			{ name: 'Delete', value: 'delete', action: 'Delete a cover letter', description: 'Permanently delete a cover letter' },
			{ name: 'Duplicate', value: 'duplicate', action: 'Duplicate a cover letter', description: 'Create a copy of a cover letter' },
			{ name: 'Export', value: 'export', action: 'Export a cover letter', description: 'Export as a standalone document' },
			{ name: 'Get', value: 'get', action: 'Get a cover letter', description: 'Get a single cover letter' },
			{ name: 'Import', value: 'import', action: 'Import a cover letter', description: 'Create from an exported document' },
			{ name: 'List', value: 'list', action: 'List cover letters', description: 'List saved cover letters' },
			{ name: 'Refresh Style', value: 'refreshStyle', action: 'Refresh cover letter style', description: 'Refresh style from a resume, preserving content' },
			{ name: 'Update', value: 'update', action: 'Update a cover letter', description: 'Update supplied fields' },
		],
		default: 'list',
	},
];

export const coverLetterFields: INodeProperties[] = [
	{
		displayName: 'Cover Letter ID',
		name: 'coverLetterId',
		type: 'string',
		required: true,
		default: '',
		displayOptions: {
			show: { resource: ['coverLetter'], operation: ['get', 'update', 'delete', 'duplicate', 'refreshStyle', 'export'] },
		},
	},
	// list
	{
		displayName: 'List Filters',
		name: 'listFilters',
		type: 'collection',
		placeholder: 'Add Filter',
		default: {},
		displayOptions: { show: { resource: ['coverLetter'], operation: ['list'] } },
		options: [
			{ displayName: 'Application ID', name: 'applicationId', type: 'string', default: '' },
			{
				displayName: 'Limit',
				name: 'limit',
				type: 'number',
				typeOptions: { minValue: 1, maxValue: 100 },
				description: 'Max number of results to return',
				default: 50,
			},
			{ displayName: 'Offset', name: 'offset', type: 'number', default: 0 },
			{ displayName: 'Resume ID', name: 'resumeId', type: 'string', default: '' },
			{ displayName: 'Search', name: 'search', type: 'string', default: '' },
		],
	},
	// create
	{
		displayName: 'Name',
		name: 'name',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show: { resource: ['coverLetter'], operation: ['create'] } },
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource: ['coverLetter'], operation: ['create'] } },
		options: [
			{ displayName: 'Application ID', name: 'applicationId', type: 'string', default: '' },
			{ displayName: 'Content', name: 'content', type: 'string', typeOptions: { rows: 6 }, default: '' },
			{ displayName: 'Recipient', name: 'recipient', type: 'string', default: '' },
			{ displayName: 'Resume ID', name: 'resumeId', type: 'string', default: '' },
			{
				displayName: 'Template',
				name: 'template',
				type: 'options',
				default: 'azurill',
				options: [
					{ name: 'Azurill', value: 'azurill' },
					{ name: 'Bronzor', value: 'bronzor' },
					{ name: 'Chikorita', value: 'chikorita' },
					{ name: 'Ditgar', value: 'ditgar' },
					{ name: 'Ditto', value: 'ditto' },
					{ name: 'Gengar', value: 'gengar' },
					{ name: 'Glalie', value: 'glalie' },
					{ name: 'Kakuna', value: 'kakuna' },
					{ name: 'Lapras', value: 'lapras' },
					{ name: 'Leafish', value: 'leafish' },
					{ name: 'Meowth', value: 'meowth' },
					{ name: 'Onyx', value: 'onyx' },
					{ name: 'Pikachu', value: 'pikachu' },
					{ name: 'Rhyhorn', value: 'rhyhorn' },
					{ name: 'Scizor', value: 'scizor' },
				],
			},
		],
	},
	// update
	{
		displayName: 'Expected Revision',
		name: 'expectedRevision',
		type: 'number',
		required: true,
		default: 1,
		displayOptions: { show: { resource: ['coverLetter'], operation: ['update', 'delete', 'refreshStyle'] } },
		description: 'Current revision of the cover letter (see Get); prevents concurrent overwrites',
	},
	{
		displayName: 'Update Fields',
		name: 'updateFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource: ['coverLetter'], operation: ['update'] } },
		options: [
			{ displayName: 'Content', name: 'content', type: 'string', typeOptions: { rows: 6 }, default: '' },
			{ displayName: 'Name', name: 'name', type: 'string', default: '' },
			{ displayName: 'Recipient', name: 'recipient', type: 'string', default: '' },
			{
				displayName: 'Template',
				name: 'template',
				type: 'options',
				default: 'azurill',
				options: [
					{ name: 'Azurill', value: 'azurill' },
					{ name: 'Bronzor', value: 'bronzor' },
					{ name: 'Chikorita', value: 'chikorita' },
					{ name: 'Ditgar', value: 'ditgar' },
					{ name: 'Ditto', value: 'ditto' },
					{ name: 'Gengar', value: 'gengar' },
					{ name: 'Glalie', value: 'glalie' },
					{ name: 'Kakuna', value: 'kakuna' },
					{ name: 'Lapras', value: 'lapras' },
					{ name: 'Leafish', value: 'leafish' },
					{ name: 'Meowth', value: 'meowth' },
					{ name: 'Onyx', value: 'onyx' },
					{ name: 'Pikachu', value: 'pikachu' },
					{ name: 'Rhyhorn', value: 'rhyhorn' },
					{ name: 'Scizor', value: 'scizor' },
				],
			},
		],
	},
	// duplicate
	{
		displayName: 'Name',
		name: 'duplicateName',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['coverLetter'], operation: ['duplicate'] } },
		description: 'Optional new name for the copy',
	},
	// refreshStyle
	{
		displayName: 'Resume ID',
		name: 'resumeId',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show: { resource: ['coverLetter'], operation: ['refreshStyle'] } },
		description: 'Resume to refresh the style from',
	},
	// copyFromResume
	{
		displayName: 'Resume ID',
		name: 'resumeId',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show: { resource: ['coverLetter'], operation: ['copyFromResume'] } },
	},
	{
		displayName: 'Section ID',
		name: 'sectionId',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show: { resource: ['coverLetter'], operation: ['copyFromResume'] } },
	},
	{
		displayName: 'Item ID',
		name: 'itemId',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show: { resource: ['coverLetter'], operation: ['copyFromResume'] } },
	},
	{
		displayName: 'Name',
		name: 'copyName',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['coverLetter'], operation: ['copyFromResume'] } },
		description: 'Optional name for the saved cover letter',
	},
	// import
	{
		displayName: 'Document (JSON)',
		name: 'document',
		type: 'json',
		required: true,
		default: '{}',
		displayOptions: { show: { resource: ['coverLetter'], operation: ['import'] } },
		description: 'An exported Reactive Resume cover-letter document',
	},
];
